export const KEY_PRESSED = 'KEY_PRESSED';
export const KEY_RELEASED = 'KEY_RELEASED';
export const DRUM_CLICKED_DOWN = 'DRUM_CLICKED_DOWN';
export const DRUM_CLICKED_UP = 'DRUM_CLICKED_UP';
export const GENRE_CHANGED = 'GENRE_CHANGED';